### ISSUE TITLE
Presentation don't respond to keys

### ISSUE THREAD

**Issue by Daniel-at-github** [markdownreveal/markdownreveal#16]
Creating the example presentation it don't respond to keys.

Environment:
OS: `Fedora 25 TwentyFive`
Kernel: `x86_64 Linux 4.10.14-200.fc25.x86_64`
Python: `3.5.3`

Commands used:
~~~ bash
mkdir markdownreveal
cd markdownreveal
mkvirtualenv --python=$(which python3) markdownreveal
pip install --upgrade markdownreveal
markdownreveal clean
cat > presentation.md <<'EOF'
% Presentation title
% Author
% YYYY-MM-DD

# First section

## Subsection

This is my first Markdownreveal presentation.

## Subsection

This is my second slide.
EOF
markdownreveal presentation.md
~~~

Chromium `Versión 57.0.2987.133 Fedora Project (64-bit)`
http://localhost:8123/#/
Tried keys:
* No action: SPACE, MAYUS + SPACE, ESC, arrows
* Open the presenter: S

Opening in a new tab you can see the slide, but cant move to other slides:
* http://localhost:8123/#/
* http://localhost:8123/#/2
* http://localhost:8123/#/2/1

Same in Firefox: `Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0`

**Comment by Daniel-at-github** [comment]
Workaround, la versión anterior funciona:
~~~ bash
pip install markdownreveal==0.1.2
~~~

**Comment by Peque** [comment]
@Daniel-at-github Thanks for reporting this bug! Apparently I uploaded the development version instead of the stable 0.1.3... :sweat_smile: 

I uploaded a new version (0.1.4). Please, try to `pip install --upgrade markdownreveal` and tell me if you still find any problems.

**Comment by Daniel-at-github** [comment]
Everithing ok now 😄

**Comment by Peque** [comment]
Awesome! :smile:
