### ISSUE TITLE
Remove docker dependency

### ISSUE THREAD

**Issue by frederik-elwert** [markdownreveal/markdownreveal#18]
The new version of DeckTape uses Puppeteer instead of PhantomJS. So it should be safe to use it without docker. Still a nightmare to install (because of NodeJS version etc.), but might be the path forward.

**Comment by Peque** [comment]
Thanks! I will have a look at it when I find some spare time. :blush:

**Comment by Peque** [comment]
@frederik-elwert Docker was removed as a dependency. Markdownreveal now uses Decktape directly underneath to export to PDF. Documentation has been updated:

https://markdownreveal.readthedocs.io/en/latest/subcommands.html#export-to-pdf
