### ISSUE TITLE
Header feature collides with pandoc tables

### ISSUE THREAD

**Issue by frederik-elwert** [markdownreveal/markdownreveal#22]
Both markdownreveal’s own header feature and the way pandoc generates tables use the `.header` CSS class. As a consequence, tables that use headers are displayed distorted.

This markdown:

```markdown
% Title
% Author
% Date

# A section

## A slide

Test text.

## A second slide

Column A | Column B
---------|---------
Cell A | Cell B
```

leads to this output:

![Screenshot of presentation](https://screenshots.firefoxusercontent.com/images/f0a23a81-5ea9-404e-b6be-f16a0e1fc764.png)

A resolution would be to change the class name for markdownreveal’s header (but this could break custom styles) or formulate the CSS rule more specific (e.g. `div.header` instead of plain `.header`, as pandoc tables use `tr.header`).

**Comment by Peque** [comment]
Thanks for reporting, and sorry for the late reply. :sweat_smile: 

It is actually an ugly bug! I will probably find some time next week to fix it. I think I will change the class name for Markdownreveal's header/footer. Even if it breaks someone's current style, it is the cleanest/safest way. After all, Markdownreveal is still marked as alpha until 1.0.0 release. :wink:

**Comment by Peque** [comment]
@frederik-elwert I think it is fixed now. Could you try to `pip install --upgrade markdownreveal` and tell me if it is fine for you too?

I bumped the version to 0.2.0 as this change is not backwards compatible and can break other people's custom styles.

**Comment by Peque** [comment]
Feel free to reopen if it is not fixed or you find any problems.

Thanks again for reporting! :blush:
