### ISSUE TITLE
Default header/title size

### ISSUE THREAD

**Issue by Peque** [markdownreveal/markdownreveal#26]
Maybe change from `2.5em` to `2em`?

Ask other users.

**Comment by Peque** [comment]
Quick survey... :blush:

I am thinking about changing the [default font size in headers](https://github.com/markdownreveal/style-default/blob/master/custom.css) from `2.5em` to `2em`. I found that 2.5 is perhaps too big and medium/long headers are many times split in multiple lines, which might look a bit ugly.

What do you think?

@Jesus89 @frederik-elwert @jjmontesl @cua-cua

**Comment by Jesus89** [comment]
LGTM!

**Comment by cua-cua** [comment]
👍

**Comment by jjmontesl** [comment]
+1, sí que están grandotes sí.

**Comment by Peque** [comment]
Done. Thanks for the feedback! :blush:
