### ISSUE TITLE
Warmup option

### ISSUE THREAD

**Issue by Peque** [markdownreveal/markdownreveal#8]
Maybe add an option to enable/disable warmup slide:

    markdownreveal --warmup presentation.md

**Comment by Steffo99** [comment]
I might be interested in developing this.
What would a warmup slide be?

**Comment by Peque** [comment]
@Steffo99 Usually an image. It is shown on the screen before starting the presentation and it could be a logo or a QR code with a link to the presentation that is about to be presented.

I think right now you can create an image in `style/warmup.svg`. If that image is there in the style folder, then it will be always shown. See the [documentation on Markdownreveal styles](https://markdownreveal.readthedocs.io/en/stable/style.html) and verify it works this way (I am currently not sure... :joy:).

Instead of always showing this image it would be great if the user could disable/enable this. In example:

- Use `--no-warmup` to avoid displaying the warmup image even if it is in the style folder.
- Use `--warmup anyimage.format` to load a specific image even if there is none in the style folder (it should override the one in the style folder if it is there too).

**Comment by Peque** [comment]
Closing this after https://github.com/markdownreveal/markdownreveal/pull/21.

That should be enough to allow flexibility and to minimize changes and maintenance burden. :blush:
